name: p7app
description: A new Flutter application for Project Seven.


version: 1.0.42+17


environment:
  sdk: ">=2.6.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  device_preview: ^0.4.4
  cupertino_icons: ^0.1.3
  provider: ^4.0.5+1
  font_awesome_flutter: ^8.8.1
  flutter_feather_icons: ^1.0.3
  rxdart: ^0.24.0
  http: ^0.12.1
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.7
  intl: ^0.16.1
  page_view_indicators: ^1.3.1
  flutter_rating_bar: ^3.0.1+1
  uuid: ^2.0.4
  image_crop: ^0.3.2
  image_picker: ^0.6.5+2
  flutter_html: ^0.11.1
  package_info: ^0.4.0+17
  dartz: ^0.9.0
  google_fonts: ^1.0.0
  bot_toast: ^2.4.1
  url_launcher: ^5.4.5
  cached_network_image: ^2.1.0+1
  flutter_image_compress: ^0.6.7
  equatable: ^1.1.1
  autocomplete_textfield: ^1.7.3
  device_id: ^0.2.0
  connectivity: ^0.4.8+2
















dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  #  mockito used for mocking
  mockito: 4.1.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/job_search_logo_sq.png"



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/google_fonts/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-RegularItalic.ttf
          style: italic