name: p7app
description: A new Flutter application for Project Seven.


version: 0.0.118+92


environment:
  sdk: ">=2.6.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

#  device_preview: ^0.4.5
  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  font_awesome_flutter: ^8.8.1
  flutter_feather_icons: ^1.0.3
  rxdart: ^0.24.1
  http: ^0.12.1
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.7+3
  intl: ^0.16.1
  page_view_indicators: ^1.3.1
  uuid: ^2.0.4
  image_crop: ^0.3.2
  image_picker: ^0.6.7+1
#  flutter_html: ^1.0.0
  package_info: ^0.4.1
  dartz: ^0.9.1
  google_fonts: ^1.1.0
  bot_toast: ^3.0.0
  url_launcher: ^5.4.10
  cached_network_image: ^2.2.0+1
  flutter_image_compress: ^0.6.8
  equatable: ^1.2.0
#  device_id: ^0.2.0
  connectivity: ^0.4.8+6
  logger: ^0.9.1
  get_it: ^4.0.2
#  searchable_dropdown: ^1.1.3
  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^1.8.1
#  animations: ^1.0.0+5
  firebase_messaging: ^6.0.16
  firebase_core: ^0.4.5
  google_maps_flutter: ^0.5.28+1
  webview_flutter: ^0.3.22+1
  charts_flutter: ^0.9.0
  shimmer: ^1.1.1
  percent_indicator: ^2.1.3

















dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  #  mockito used for mocking
  mockito: 4.1.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/job_search_logo_sq.png"



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/google_fonts/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-RegularItalic.ttf
          style: italic