name: p7app
description: A new Flutter application for Project Seven.

version: 1.0.22+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #  Dev tools -> different size of screen preview ###############
  device_preview: ^0.4.4


  #  Default icons asset for Cupertino widgets
  cupertino_icons: ^0.1.3

  #A mixture between dependency injection and state management
  provider: ^4.0.5

  #  The Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^8.8.1
  flutter_feather_icons: ^1.0.3

  # reactiveX api for asynchronous programming.
  rxdart: ^0.24.0


  #   checks for internet by opening a socket to a list of specified addresses,
  #  data_connection_checker: ^0.3.4

  #  A composable, cross-platform, Future-based API for making HTTP requests.
  http: ^0.12.0+4

  #  Execute code after the first layout of your widget has been performed,
  after_layout: ^1.0.7+2

  #providing a persistent store for simple data
  shared_preferences: ^0.5.6+3
  #internationalization and localization facilities --> used for DateFormat
  intl: ^0.16.1


  #  track page view widget index
  page_view_indicators: ^1.3.1

  #  rating bar -> Used for star rating
  flutter_rating_bar: ^3.0.1+1

  #  Unique id generator
  uuid: ^2.0.4

  #  Image Cropper
  image_crop: ^0.3.2

  #   peak image form gallery and take capture image using camera
  image_picker: ^0.6.5

  #  Modal Progress hud (Heads Up Display) to show progress on to of screen
  modal_progress_hud: ^0.1.3

  #  Html formatting
  flutter_html: ^0.11.1

  #  keep screen always weak
  wakelock:

  #  to retrieve information about app
  package_info: ^0.4.0+16

  #  Functional programming in Dart
  dartz: 0.8.8

  #  JSON serialization and deserialization.
#  json_annotation: ^2.0.0

  #A package to include fonts from fonts.google.com
  google_fonts: ^0.5.0+1

  #  flutter toast library!
  bot_toast: ^2.4.0

  #URL launcher
  url_launcher: ^5.4.2
















dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  #  mockito used for mocking
  mockito: 4.1.0
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/job_search_logo_sq.png"



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/google_fonts/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-RegularItalic.ttf
          style: italic