name: p7app
description: A new Flutter application for Project Seven.


version: 1.1.24+229


environment:
  sdk: ">=2.8.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

#  device_preview: ^0.4.5
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  font_awesome_flutter: ^8.8.1
  flutter_feather_icons: ^1.0.3
  rxdart: ^0.24.1
  http: ^0.12.2
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.10
  intl: ^0.16.1
  page_view_indicators: ^1.3.1
  uuid: ^2.2.2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+7
  package_info: ^0.4.3
  dartz: ^0.9.1
  google_fonts: ^1.1.0
  bot_toast: ^3.0.4
  url_launcher: 5.5.0
  cached_network_image: ^2.3.2+1
  flutter_image_compress: 0.6.8
  equatable: ^1.2.5
#  device_id: ^0.2.0
#  connectivity: ^0.4.9+2
  logger: ^0.9.2
  get_it: ^4.0.4
  flutter_typeahead: ^1.8.8
  dropdown_search: ^0.4.4
#  animations: ^1.0.0+5
  firebase_messaging: ^7.0.0
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  google_maps_flutter: ^0.5.32
  google_maps_flutter_web: ^0.1.0+2
  webview_flutter: ^0.3.22+1
  charts_flutter: ^0.9.0
  shimmer: ^1.1.1
  percent_indicator: ^2.1.6
  jwt_decode: ^0.1.0
  flutter_cache: ^0.0.6
  flutter_widget_from_html_core: ^0.5.0+3
  quill_delta: ^1.1.0
  notustohtml: ^0.0.7
  zefyr: ^0.11.0
  flutter_linkify: ^3.1.3
  social_share: ^2.0.5
  socket_io: ^0.9.4
  socket_io_client: ^0.9.11
  device_info: ^0.4.2+7
  google_sign_in: ^4.5.3
  get: ^3.10.2




dependency_overrides:
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr





dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_driver:
    sdk: flutter
  #  mockito used for mocking
  mockito: 4.1.0
  flutter_launcher_icons: ^0.8.0
#  flutter_flavorizr: ^1.0.3
#
#flavorizr:
#  app:
#    android:
#      flavorDimensions: "flavor-type"
#    ios:
#
#  flavors:
#    prod:
#      app:
#        name: "Job Express"
#
#      android:
#        applicationId: "com.ishraak.jobexpress"
#
#      ios:
#        bundleId: "com.ishraak.jobexpress"
#
#    dev:
#      app:
#        name: "Job Express Dev"
#      android:
#        applicationId: "com.ishraak.p7app"
#      ios:
#          bundleId: "com.ishraak.p7app"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_sq.png"



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/certification/

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 800
#        - asset: assets/fonts/Roboto-RegularItalic.ttf
#          style: italic







