class JobDetailModel{
  String status;
  bool is_applied;
  String job_id;
  String title;
  String industry;
  String employment_status;
  String job_location;
  String experience;
  String salary_min;
  String salary_max;
  String qualification;
  String gender;
  String currency;
  String vacancy;
  String application_deadline;
  String descriptions;
  String responsibilities;
  String education;
  String salary;
  String other_benefits;
  String company_name;
  String division;
  String district;
  String zipcode;
  String company_location;
  String company_profile;
  String latitude;
  String longitude;
  String raw_content;
  String web_address;
  String terms_and_conditions;
  String created_date;
  String job_skills;

}